### ISSUE TITLE
[BUG] [RHEL] GPG signature could not be verified for Kubernetes repository

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#3034]
**Describe the bug**
There is a problem with gpg signatures for the Kubernetes repository. The download-requirements script simply fails on RHEL environments.

**All epicli versions are affected (RHEL 7 and CentOS 7 installations).**
```
kubernetes/signature                                                                                                                 |  844 B  00:00:00
Retrieving key from https://packages.cloud.google.com/yum/doc/yum-key.gpg
Importing GPG key 0x7AA99B80:
 Userid     : "Rapture Automatic Signing Key (cloud-rapture-signing-key-2022-03-07-08_01_01.pub)"
 Fingerprint: e89b faec 34d3 1829 362f 7f7b 5668 44f3 7aa9 9b80
 From       : https://packages.cloud.google.com/yum/doc/yum-key.gpg
Retrieving key from https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
kubernetes/signature                                                                                                                 | 1.4 kB  00:00:03 !!!
https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for kubernetes
Trying other mirror.
```

**How to reproduce**
1. Try to deploy any RHEL 7/CentOS 7 cluster (repository vm is enough).

or run:
```
docker run -it amd64/centos:7.9.2009

cat <<EOF | tee /etc/yum.repos.d/kubernetes.repo
[kubernetes]
name=Kubernetes
baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

yum install -y kubectl

```

Original issue: https://github.com/kubernetes/website/issues/32207

Workaround:
Set `repo_gpgcheck=0` for kubernetes repo, however it's not recommended for security reasons.

RHEL 8 and CentOS 8 seem not to be affected.
The differrence is that there is `gpg (GnuPG) 2.2.20` and on RHEL7 it is `gpg (GnuPG) 2.0.22`.

**Expected behavior**
There should be no issues adding kubernetes repository.

**Environment**
- Cloud provider: [all]
- OS: [RHEL 7, CentOS 7]

**epicli version**: all

**Additional context**

---

**DoD checklist**

- Changelog
  - [x] updated
  - [ ] not needed
- COMPONENTS.md
  - [ ] updated
  - [x] not needed
- Schema
  - [ ] updated
  - [x] not needed
- Backport tasks
  - [ ] created
  - [x] not needed
- Documentation
  - [ ] added
  - [ ] updated
  - [x] not needed
- [ ] Feature has automated tests
- [ ] Automated tests passed (QA pipelines)
  - [x] apply
  - [ ] upgrade
  - [ ] backup/restore
- [ ] Idempotency tested
- [x] All conversations in PR resolved

**Comment by seriva** [comment]
Should be fixed for 1.0.3 and 1.3.1 releases.

**Comment by erzetpe** [comment]
This option with repo_gpgcheck=0 may not be the worse thing as still we are validating the packages.

**Comment by to-bar** [comment]
1) The use of gnupg-2.2 doesn't solve the issue (tried static version based on https://people.kernel.org/monsieuricon/run-gnupg-2-2-17-on-your-el7-system).
2) Issue is somehow related to `yum` since it doesn't occur with `dnf` (can be installed on CentOS 7).
3) K8s repository uses https endpoint so setting `repo_gpgcheck=0` seems to be fine.
